name: Run Julia Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'  # Adjust if using a different version

      - name: Install dependencies
        run: |
          julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: |
          julia -e 'using Pkg; Pkg.test()'

