name: Run Julia Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      - name: Verify Project.toml Exists
        run: |
          ls -l $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE/Project.toml || echo "Project.toml not found"

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          julia -e 'using Pkg; Pkg.activate("."); Pkg.test()'

